name: Lean build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          build-args: "DistanceSimilarity"
          test: false
          lint: false
      - name: Print axioms
        run: lake env lean verify/Axioms.lean
